# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: Node CI

on:
  push:
    paths:
      - "**Dockerfile**"
jobs:
  Build-And-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, push
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: public
      - name: Build container image
        uses: docker/build-push-action@1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: AdamBrodin/github-actions-for-packages/tic-tac-toe
          tag_with_sha: true
